[package]
name = "braid_utils"
version = "0.1.0"
authors = ["Baxter Eaves <bax@redpoll.ai>"]
edition = "2018"

[dependencies]
rand = {version="0.5.0", features=["serde1"]}
rv = { git = "https://gitlab.com/baxe/rv", branch = "dev" }

[dev-dependencies]
approx = "0.3.1"
