[package]
name = "lace"
version = "0.10.0"
authors = ["Redpoll"]
build = "build.rs"
edition = "2024"
exclude = ["resources/test/*", "target/*"]
rust-version = "1.89.0"
license = "MIT"
homepage = "https://www.lace.dev/"
repository = "https://github.com/promised-ai/lace"
description = "A probabilistic cross-categorization engine"

[build-dependencies]
dirs = "5"

[dependencies]
rv = { workspace = true }
dirs = { version = "5", optional = true }
enum_dispatch = { workspace = true }
num = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rand_xoshiro = { workspace = true }
rand_distr = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
special = { workspace = true }
itertools = { workspace = true }
maplit = { workspace = true }
indexmap = { workspace = true }
thiserror = { workspace = true }
indicatif = { workspace = true }
ctrlc = { workspace = true, optional = true }
polars = { workspace = true }
# Bring in time JUST to pass the RUSTSEC issue with time used by plotly
time = { workspace = true }

[dev-dependencies]
clap = { workspace = true }
approx = { workspace = true }
tempfile = { workspace = true }
criterion = { workspace = true }
indoc = { workspace = true }
plotly = { workspace = true }

[features]
default = ["examples"]
examples = ["dep:dirs"]
ctrlc_handler = ["dep:ctrlc"]
bencher = ["formats", "examples"]
formats = ["polars/json", "polars/ipc", "polars/decompress", "polars/parquet"]

[[example]]
name = "animals"
required-features = ["examples"]

[[example]]
name = "satellites"
required-features = ["examples"]

[[example]]
name = "update"
required-features = ["examples"]

[[test]]
name = "engine"
required-features = ["examples"]

[[test]]
name = "workflow"
required-features = ["formats"]

[profile.release]
lto = "fat"

[profile.bench]
lto = "fat"
codegen-units = 1

[[bench]]
name = "insert_data"
harness = false

[[bench]]
name = "oracle_fns"
harness = false
required-features = ["examples"]

[[bench]]
name = "state_types"
harness = false

[[bench]]
name = "all_algs"
harness = false

[[bench]]
name = "feature_prior_update"
harness = false

[[bench]]
name = "massflip"
hequired-features = ["examples"]
