---
geweke:
    settings:
        - ncols: 4
          nrows: 50
          row_alg: finite_cpu
          col_alg: finite_cpu
          transitions:
              - column_assignment
              - row_assignment
              - state_alpha
              - view_alphas
              - feature_priors
          cm_types:
              - continuous
              - continuous
              - continuous
              - continuous
    n_iters: 5000
    lag: 10
