---
id: "geweke"
geweke:
  settings:
    finite_cpu_quick:
      ncols: 10
      nrows: 50
      transitions:
        - column_assignment: slice
        - row_assignment: slice
        - component_params
        - state_alpha
        - view_alphas
        - feature_priors
      cm_types:
        - continuous
        - continuous
        - continuous
        - continuous
        - continuous
        - categorical
        - categorical
        - categorical
        - categorical
        - categorical
  n_iters: 1000
  n_runs: 10
  lag: 10
