---
geweke:
    settings:
        - ncols: 4
          nrows: 50
          row_alg: finite_cpu
          col_alg: finite_cpu
          cm_types:
            - continuous
            - continuous
            - continuous
            - continuous
    n_iters:
        50000
