workspace:
    base: /rust

pipeline:
    # unit:
    #     environment:
    #         - CARGO_HOME=/var/cache/drone/cargo
    #         - RUST_BACKTRACE=1
    #     image: "rustlang/rust:nightly"
    #     commands:
    #         - rustc --version && cargo --version  # Print version info for debugging
    #         - chmod +x scripts/test-setup.sh
    #         - ./scripts/test-setup.sh
    #         - cargo test --jobs 1            # Run serial for more readable errors
    regression:
        environment:
            - CARGO_HOME=/var/cache/drone/cargo
            - RUST_BACKTRACE=1
        image: "braid_drone"
        commands:
            - export FILENAME=`date +%s`_normal.json
            - rustc --version && cargo --version  # Print version info for debugging
            - cargo build --release
            - RUST_LOG=info target/release/braid regression -o $FILENAME resources/regression/configs/normal.yaml
            - aws s3 cp $FILENAME s3://redpoll/braid/regression/data/$FILENAME
            - curl -u $${APP_AUTH} -F "file=@$FILENAME;type=text/json" http://bax.pythonanywhere.com/upload
        secrets: [ app_auth ]
