image: "rustlang/rust:nightly"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

stages:
  - format
  - test
  - benchmark

format:
  stage: format
  before_script:
    - rustup install nightly-2019-07-09 --no-self-update
    - rustup override set nightly-2019-07-09
    - rustup component add rustfmt --toolchain nightly-2019-07-09
  script:
    - rustfmt --check

test:nightly:
  stage: test
  script:
  - rustc --version && cargo --version  # Print version info for debugging
  - chmod +x scripts/test-setup.sh
  - ./scripts/test-setup.sh
  - cargo build
  - ./target/debug/braid regen-examples  # Get examples built before tests
  - time cargo test --all                # Run serial for more readable errors

build:benchmarks:
  stage: benchmark
  script:
  - cargo bench --no-run
