image: "rust:1.41"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

stages:
  - format
  - test
  # - benchmark

format:
  stage: format
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

test:
  stage: test
  script:
  - rustc --version && cargo --version  # Print version info for debugging
  - cargo build
  - ./target/debug/braid regen-examples  # Get examples built before tests
  - time cargo test --all                # Run serial for more readable errors

# build:benchmarks:
#   stage: benchmark
#   script:
#   - cargo bench --no-run
