image: "rustlang/rust:nightly"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

stages:
  - format
  - test

format:
  stage: format
  before_script:
    - rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
  script:
    - rustfmt --check

test:nightly:
  stage: test
  script:
  - rustc --version && cargo --version  # Print version info for debugging
  - chmod +x scripts/test-setup.sh
  - ./scripts/test-setup.sh
  - time cargo test --all --jobs 1      # Run serial for more readable errors
