image: "rust:1.45"

variables:
  CARGO_HOME: /cargo
  RUST_BACKTRACE: 1

stages:
  - format
  - test
  - publish

default:
  before_script:
    - mkdir $CARGO_HOME && touch $CARGO_HOME/config
    - echo "[registries]" >> $CARGO_HOME/config &&
      echo "redpoll-crates = { index = \"https://dl.cloudsmith.io/${CLOUDSMITH_KEY}/redpoll/crates/cargo/index.git\" }" >> $CARGO_HOME/config

format:
  stage: format
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

test:
  stage: test
  script:
    # Print version info for debugging
    - rustc --version && cargo --version                          
    - time cargo build
    # Get examples built before tests. The quality of inference is important =
    # for animals, but not for satellites. To save time, run satellites for a
    # short amount of time.
    - time ./target/debug/braid regen-examples --timeout 120 --examples animals 
    - time ./target/debug/braid regen-examples --timeout 10 --examples satellites 
    # Run serial for more readable errors
    - time cargo test --all                                       

publish:crates:
  stage: publish
  only:
    - tags
  except:
    - branches
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip
    - pip3 install --upgrade cloudsmith-cli
    - bash publish.sh

publish:image:
  stage: publish
  image: docker:19.03.1
  services:
  - docker:19.03.0-dind
  only:
    - tags
  except:
    - branches
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg CLOUDSMITH_KEY=$CLOUDSMITH_KEY -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
