image: "rustlang/rust:nightly"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:cargo:
  script:
  - rustc --version && cargo --version
  - chmod +x scripts/test-setup.sh
  - ./scripts/test-setup.sh
  - RUST_BACKTRACE=1 time cargo test --jobs 1
