image: "rustlang/rust:nightly"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:cargo:
  script:
  - rustc --version && cargo --version  # Print version info for debugging
  - time cargo test --jobs 1            # Run serial for more readable errors
  - cargo bench
