image: "rust:1.41"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

stages:
  - format
  - test
  # - benchmark

default:
  before_script:
    - mkdir $CARGO_HOME && touch $CARGO_HOME/config
    - echo "[registries]" >> $CARGO_HOME/config &&
      echo "redpoll-crates = { index = \"https://dl.cloudsmith.io/${CLOUDSMITH_KEY}/redpoll/crates/cargo/index.git\" }" >> $CARGO_HOME/config

format:
  stage: format
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

test:
  stage: test
  script:
  - rustc --version && cargo --version  # Print version info for debugging
  - cargo build
  - ./target/debug/braid regen-examples  # Get examples built before tests
  - time cargo test --all                # Run serial for more readable errors

# build:benchmarks:
#   stage: benchmark
#   script:
#   - cargo bench --no-run
