[package]
name = "braid"
version = "0.1.0"
authors = ["Baxter Eaves <baxyjr@gmail.com>"]


[lib]
name = "braid"
path = "src/braid/lib.rs"


[[bin]]
name = "braid"
test = false
doc = false


[dependencies]
itertools = "*"
num = "*"
rand = "*"
time = "*"
approx = "*"
rayon = "*"
serde = "*"
serde_derive = "*"
serde_yaml = "*"
serde_json = "*"
rmp-serde = "*"
rusqlite = "*"
hyper = "*"
futures = "*"
pbr = "1.0.0"
clap = {version = "*", features = ["yaml"]}
csv = "1.0.0-beta.5"
special = "0.7.7"
# ocl = "0.15"


[dev-dependencies]
criterion = "0.2.0"
serde_test = "1.0.24"
