[package]
name = "braid"
version = "0.1.0"
authors = ["Baxter Eaves <baxyjr@gmail.com>"]


[lib]
name = "braid"
path = "src/braid/lib.rs"


[[bin]]
name = "braid"
test = false
doc = false


[dependencies]
itertools = "*"
num = "*"
rand = "*"
time = "*"
approx = "*"
rayon = "*"
serde = "*"
serde_derive = "*"
serde_yaml = "*"
serde_json = "*"
rusqlite = "*"
jsonrpc-core = "*"
jsonrpc-http-server = "*"
progress = "*"
clap = {version = "*", features = ["yaml"]}
# ocl = "0.15"


[dev-dependencies]
criterion = "0.1.0"
serde_test = "1.0.24"
