[package]
name = "braid"
version = "0.1.0"
authors = ["Baxter Eaves <baxyjr@gmail.com>"]

[dependencies]
itertools = "*"
num = "0.1.40"
rand = "*"
time = "*"
approx = "0.1.1"
rayon = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7.2"
# ocl = "0.15"

[dev-dependencies]
criterion = "0.1.0"
serde_test = "1.0.24"
