[package]
name = "braid"
version = "0.12.0"
authors = ["Baxter Eaves <bax@redpoll.ai>"]
build = "build.rs"
edition = "2018"

[build-dependencies]
braid_flippers = { path = "src/braid_flippers" }
rand = "0.6.0"
rand_xoshiro = "0.1"

[lib]
name = "braid"
path = "src/lib.rs"

[[bin]]
name = "braid"
path = "bin/main.rs"

[dependencies]
itertools = "0.8.0"
num = "0.2.0"
rand_xoshiro = "0.2"
rand = {version="0.6", features=["serde1"]}
time = "0.1"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1"
bincode = "1.1"
rusqlite = "0.18"
futures = "<0.2.0"
structopt = "0.2"
csv = "1"
special = "0.8"
indicatif = "0.11"
log = "0.4"
env_logger = "0.5"
regex = "1.1"
num_cpus = "1"
rv = { version = "0.6.0", features = ["serde_support"] }
maplit = "1"
braid_utils = { git = "ssh://gitlab.com/Redpoll/braid_utils.git", tag = "v0.3.0" }
braid_stats = { git = "ssh://gitlab.com/Redpoll/braid_stats.git", branch = "labeler-type" }
braid_codebook = { git = "ssh://gitlab.com/Redpoll/braid_codebook.git", branch = "labeler-type" }
braid_flippers = { path = "src/braid_flippers" }
enum_dispatch = "0.1.3"


[dev-dependencies]
approx = "0.3"
serde_test = "1"
tempfile = "3"

[profile.bench]
codegen-units = 1
