[package]
name = "braid"
version = "0.1.11"
authors = ["Baxter Eaves <baxyjr@gmail.com>"]

[lib]
name = "braid"
path = "src/lib.rs"

[[bin]]
name = "braid_regression"
path = "regression/main.rs"

[dependencies]
itertools = "*"
num = "*"
rand = {version="0.5.0", features=["serde1"]}
time = "*"
approx = "*"
rayon = "*"
serde = "*"
serde_derive = "*"
serde_yaml = "*"
serde_json = "*"
rmp-serde = "*"
rusqlite = "*"
futures = "<0.2.0"
clap = {version = "*", features = ["yaml"]}
csv = "1.0.0-beta.5"
special = "0.7.7"
# ocl = "0.15"
indicatif = "*"
log = "0.4.0"
env_logger = "0.5.10"
regex = "1.0.0"
num_cpus = "1.0"

[dev-dependencies]
criterion = "0.2.0"
serde_test = "1.0.24"

[[bench]]
name = "bench_misc"
harness = false

[[bench]]
name = "bench_gauss"
harness = false

[[bench]]
name = "bench_view"
harness = false
