[package]
name = "braid"
version = "0.4.0"
authors = ["Baxter Eaves <baxyjr@gmail.com>"]
build = "build.rs"

[build-dependencies]
rayon = "1.0.2"
rand = "0.5.0"

[lib]
name = "braid"
path = "src/lib.rs"

[[bin]]
name = "braid"
path = "bin/main.rs"

[dependencies]
itertools = "*"
num = "*"
rand = {version="0.5.0", features=["serde1"]}
time = "*"
approx = "*"
rayon = "1.0.0"
serde = "*"
serde_derive = "*"
serde_yaml = "*"
serde_json = "*"
rmp-serde = "*"
rusqlite = "*"
futures = "<0.2.0"
structopt = "0.2.12"
csv = "1.0.0-beta.5"
special = "0.7.8"
indicatif = "*"
log = "0.4.0"
env_logger = "0.5.10"
regex = "1.0.0"
num_cpus = "1.0"
rv = { git = "https://gitlab.com/baxe/rv", branch = "dev", features = ["serde_support"] }
proc-macro2 = "*"
maplit = "1.0.1"

[dev-dependencies]
serde_test = "1.0.24"
tempfile = "3.0.4"
