[package]
name = "braid_consts"
version = "0.2.2"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
# rv = "0.7.2"
rv = {git = "https://gitlab.com/baxe/rv", branch = "v0.8.0-beta" }
