[package]
name = "braid_flippers"
version = "0.1.3"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
rand = {version="0.7", features=["serde1"]}
rayon = "1"

[dev-dependencies]
criterion = "0.2"
rand_core = "0.5.0"
rand_xoshiro = "0.4"

[[bench]]
name = "benches"
harness = false
