[package]
name = "pylace"
version = "0.10.2"
edition = "2024"
license = "MIT"
rust-version = "1.89.0"

[lib]
name = "lace"
crate-type = ["cdylib"]

[dependencies]
lace = { workspace = true }
rand = { workspace = true }
rand_xoshiro = { workspace = true }
pyo3 = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
polars = { workspace = true }
polars-arrow = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }

[package.metadata.maturin]
name = "lace.core"

[lints.clippy]
doc_link_with_quotes = "allow"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
doc_markdown = "allow"
