[package]
name = "braid_utils"
version = "0.13.3"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
rand = {version="0.8", features=["serde1"]}
rv = "0.15.0-rc.1"

[dev-dependencies]
approx = "0.5.1"
