[package]
name = "braid_codebook"
version = "0.5.5"
authors = ["Baxter Eaves <bax@redpoll.ai>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.89", features = ["derive"] }
serde_yaml = "0.8.8"
braid_stats = { path = "../braid_stats" }
maplit = "1.0.1"
rv = { git = "https://gitlab.com/baxe/rv", branch = "dev", features = ["serde_support"] }
csv = "1.0.0-beta.5"
rand = {version="0.5.0", features=["serde1"]}
