[package]
name = "braid_utils"
version = "0.4.4"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
rand = {version="0.7", features=["serde1"]}
rv = {git = "http://gitlab.com/baxe/rv", branch = "v0.8.0-beta" }

[dev-dependencies]
approx = "0.3.1"
