[package]
name = "braid_utils"
version = "0.7.0"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
rand = {version="0.7", features=["serde1"]}
rv = "0.9.2"

[dev-dependencies]
approx = "0.3"
