[package]
name = "braid_utils"
version = "0.5.0"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
rand = {version="0.7", features=["serde1"]}
rv = "0.8.3"

[dev-dependencies]
approx = "0.3"
