[package]
name = "braid_utils"
version = "0.4.2"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
rand = {version="0.6", features=["serde1"]}
rv = "0.7.1"

[dev-dependencies]
approx = "0.3.1"
