[package]
name = "braid_utils"
version = "0.3.1"
authors = ["Baxter Eaves <bax@redpoll.ai>"]
edition = "2018"

[dependencies]
rand = {version="0.6", features=["serde1"]}
rv = "0.6.1"

[dev-dependencies]
approx = "0.3.1"
