[package]
name = "braid_utils"
version = "0.10.0"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
rand = {version="0.8", features=["serde1"]}
rv = "0.12.0-rc.1"

[dev-dependencies]
approx = "0.3"
