[package]
name = "braid_flippers"
version = "0.1.2"
authors = ["Baxter Eaves <bax@redpoll.ai>"]
edition = "2018"

[dependencies]
rand = {version="0.6", features=["serde1"]}
rayon = "1"

[dev-dependencies]
criterion = "0.2"
rand_xoshiro = "0.3.0"

[[bench]]
name = "benches"
harness = false
