[package]
name = "braid_data"
version = "0.1.0"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]

[dev-dependencies]
rand = {version="0.7", features=["serde1"]}
criterion = "0.2"
