image: "rustlang/rust:nightly"

variables:
  CARGO_HOME: /cargo
  RUST_BACKTRACE: 1

stages:
  - test
  - publish

default:
  before_script:
    # set up cloudsmith registry
    - mkdir $CARGO_HOME && touch $CARGO_HOME/config
    - echo "[registries]" >> $CARGO_HOME/config &&
      echo "redpoll-crates = { index = \"https://dl.cloudsmith.io/${CLOUDSMITH_KEY}/redpoll/crates/cargo/index.git\" }" >> $CARGO_HOME/config
    # Setting up SSH to grab private repos
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

cargo:test:
  stage: test
  script:
    # get nightly that won't break everything
    # - rustup install nightly-2020-02-05 --no-self-update
    # - rustup override set nightly-2020-02-05
    - cargo test

publish:crates:
  stage: publish
  only:
    - tags
  except:
    - branches
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip
    - pip3 install --upgrade cloudsmith-cli
    - bash publish.sh

publish:image:
  stage: publish
  image: docker:19.03.1
  services:
  - docker:19.03.0-dind
  only:
    - tags
  except:
    - branches
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  before_script:
    - docker info
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg CLOUDSMITH_KEY=$CLOUDSMITH_KEY -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
