[package]
name = "braid_codebook"
version = "0.4.0"
authors = ["Baxter Eaves <bax@redpoll.ai>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.89", features = ["derive"] }
serde_yaml = "0.8.8"
braid_stats = { path = "../braid_stats" }
braid_utils = { path = "../braid_utils" }
maplit = "1.0.1"
rv = { version = "0.6.1", features = ["serde_support"] }
csv = "1.0.0-beta.5"
rand = {version="0.5.0", features=["serde1"]}
