[package]
name = "braid_codebook"
version = "0.6.1"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.89", features = ["derive"] }
serde_yaml = "0.8.8"
braid_consts = { path = "../braid_consts" }
braid_stats = { path = "../braid_stats" }
braid_utils = { path = "../braid_utils" }
maplit = "1.0.1"
rv = { git="https://gitlab.com/baxe/rv", tag = "v0.7.0rc1", features = ["serde_support"] }
csv = "1.0.0-beta.5"
rand = {version="0.6", features=["serde1"]}
