[package]
name = "braid_codebook"
version = "0.7.0"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
braid_consts = { path = "../braid_consts" }
braid_stats = { path = "../braid_stats" }
braid_utils = { path = "../braid_utils" }
maplit = "1"
rv = { version = "0.8.2", features = ["serde_support"] }
csv = "1.0.0-beta.5"
rand = {version="0.7", features=["serde1"]}

[dev-dependencies]
indoc = "*"
