[package]
name = "braid_stats"
version = "0.5.5"
authors = ["Baxter Eaves <bax@redpoll.ai>"]
edition = "2018"

[dependencies]
special = "0.7.8"
rand = {version="0.5.0", features=["serde1"]}
rv = { git = "https://gitlab.com/baxe/rv", branch = "dev", features = ["serde_support"] }
itertools = "0.8.0"
rayon = "1.0.0"
num_cpus = "1.0"
serde = { version = "1.0.89", features = ["derive"] }
braid_utils = { path = "../braid_utils" }

[dev-dependencies]
approx = "0.3.1"
