[package]
name = "lace_consts"
version = "0.1.0-alpha.1"
authors = ["Promied AI"]
edition = "2021"

[dependencies]
# rv = { version = "0.15.0-rc.1", features = ["serde1", "arraydist"]}
rv = { path = "/Users/bax/Documents/redpoll/rv", features = ["serde1", "arraydist", "datum"]}
