[package]
name = "braid_consts"
version = "0.8.1"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
# rv = { version = "0.15.0-rc.1", features = ["serde1", "arraydist"]}
rv = { path = "/Users/bax/Documents/redpoll/rv", features = ["serde1", "arraydist", "datum"]}
