[package]
name = "braid_geweke"
version = "0.2.0"
authors = ["Redpoll, LLC <info@redpoll.ai>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
braid_stats = { path = "../braid_stats" }
braid_utils = { path = "../braid_utils" }
indicatif = "0.11"
rand = { version="0.7", features=["serde1"] }
