[package]
name = "braid_geweke"
version = "0.1.0"
authors = ["Baxter Eaves <bax@redpoll.ai>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.89", features = ["derive"] }
serde_yaml = "0.8"
braid_stats = { path = "../braid_stats" }
braid_utils = { path = "../braid_utils" }
indicatif = "0.11"
rand = { version="0.6.0", features=["serde1"] }
