name: 'Check changelog for adhereance to keep-a-changelog'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'CHANGELOG.md'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup JBang
        uses: jbangdev/setup-jbang@main

      - run: |
          jbang trust add https://github.com/nbbrd/jbang-catalog/
          jbang heylogs@nbbrd check --format github-actions --rule=duplicate-items:OFF CHANGELOG.md
