name: "Python: Build and Test"

on:
  push:
    tags:
      - python-*
  workflow_dispatch:
  pull_request:
    paths:
      - "lace/**"
      - "pylace/**"
      - "book/**"
      - ".github/workflows/python-build-test.yaml"
      - ".github/scripts/run_code_in_mdfile.py"
      - ".github/scripts/find_compatible_wheel.py"

jobs:
  lint-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pylace

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Check format (black)
        run: uv tool run black --check --diff .

      - name: Lint Check (ruff)
        run: uv tool run ruff check --diff .

      - name: Check Minimum Supported Python Version (vermin)
        run: uv tool run vermin --target=3.10- --no-tips --violations .

  lint-rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pylace

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./pylace -> target"

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        env:
          RUSTFLAGS: -C debuginfo=0 # Do not produce debug symbols to keep memory usage down
        run: cargo clippy

      - name: Install audit
        run: cargo install cargo-audit

      - name: Run audit
        working-directory: lace
        run: cargo audit -f Cargo.lock

  build:
    needs: ["lint-python", "lint-rust"]
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python_version }}
          working-directory: pylace

      - name: Run Tests
        run: uv run --project pylace pytest --cov=pylace/lace --doctest-modules pylace/tests

      - name: Build Wheel
        run: uv run --project pylace maturin build --release --out dist --manifest-path pylace/Cargo.toml

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python_version }}
          path: dist

  merge:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheels
          pattern: wheels-*

  test-mdbook-python:
    name: Test MDBook Python Snippets
    runs-on: ubuntu-latest
    needs: [merge]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install codedown
        run: npm install -g codedown

      - name: Install Wheel
        run: |
          pip install packaging
          WHEEL_FILE=$(python3 .github/scripts/find_compatible_wheel.py pylace ./dist)
          echo "Installing $WHEEL_FILE"
          pip install $WHEEL_FILE

      - name: Test MDBook Code Samples (Python)
        env:
          FORCE_COLOR: 1
        run: |
          pip install termcolor yq
          NEW_VERSION=$(tomlq -r .package.version < pylace/Cargo.toml)
          python3 .github/scripts/run_code_in_mdfile.py directory python book $NEW_VERSION --exclusion-file .github/resources/mdbook_exclusions.txt

  test-mdbook-build:
    name: Test MDBook Building
    runs-on: ubuntu-latest
    needs: [merge]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./pylace -> target"

      - name: Install preprocessor
        working-directory: book/lace_preprocess_mdbook_yaml
        run: cargo install --bins --locked --path .

      - name: Install mdBook
        run: cargo install mdbook --version ^0.4

      - name: Configure the book in test mode and build
        working-directory: book
        run: |
          cat book.toml book.test.toml > book.toml.tmp
          mv book.toml.tmp book.toml
          mdbook build . -d ./html

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/python-')
    needs: [merge, test-mdbook-python, test-mdbook-build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Branch
        env:
          NEW_VERSION: ${{github.ref_name}}
        run: |
          git fetch origin master
          git tag --merged origin/master | grep $NEW_VERSION
      - name: Check Semver
        working-directory: pylace
        env:
          NEW_VERSION: ${{github.ref_name}}
        run: |
          pip install yq
          DEPLOYING_VERSION=$(echo "$NEW_VERSION" | perl -lpe 's/^python-//')
          find . -name Cargo.toml -exec tomlq -r .package.version {} \; | xargs -n 1 test "$DEPLOYING_VERSION" =
          find . -name pyproject.toml   -exec tomlq -r .project.version {} \; | xargs -n 1 test "$DEPLOYING_VERSION" =
      - uses: actions/download-artifact@v4
        id: download-wheels
        with:
          name: wheels
          path: wheels
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1.40.2
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          working-directory: ${{steps.download-wheels.outputs.download-path}}
          command: upload
          args: --skip-existing *
