# we run these in series so as to minimize the fetching/compilation costs

name: Check Pull Request

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-pull-request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Check lace
      uses: actions-rs/cargo@v1
      with:
        command: check 
        args: --manifest-path lace/Cargo.toml
    - name: Check lace formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all --check --manifest-path lace/Cargo.toml
    - name: Run clippy on lace
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args:  --manifest-path lace/Cargo.toml
    - name: Install extra cargo tools
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-audit cargo-semver-checks
    - name: Audit lace security
      uses: actions-rs/cargo@v1
      with:
        command: audit
        args: -f lace/Cargo.lock
    - name: Check for semver-incompatibilities within lace
      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
      uses: actions-rs/cargo@v1
      with:
        command: semver-checks
        args: check-release --manifest-path lace/Cargo.toml --baseline-rev master 
    - name: Run lace tests
      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path lace/Cargo.toml --all
    - name: Compile benchmark tests (but do not run)
      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
      uses: actions-rs/cargo@v1
      with:
        command: bench
        args: --manifest-path lace/Cargo.toml --no-run
    - name: Set up Python 3.10
      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python dependencies
      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
      run: |
        python -m pip install --upgrade pip
        pip install pytest maturin pyarrow polars pandas scipy plotly
    - name: Check python formatting with black
      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
      uses: psf/black@stable
      with:
        options: --check --verbose
        src: pylace/lace
    - name: Build pylace
      if: success() || failure()
      run: |
        maturin develop --release -m pylace/core/Cargo.toml
    - name: Test with pytest
      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
      run: |
        pytest pylace
    - name: Remove failure skips. YOU CANNOT MERGE TO MASTER YET
      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
      run: |
        false